name: Publish to npm
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  handle-contributors-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout with PAT authentication (FIXED)
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: vikas965/pattern-id-generator
          fetch-depth: 0  # Get complete history for version bumping

      # Step 2: Configure Git identity
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Step 3: Add contributor
      - name: Update contributors
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          sudo apt-get install -y jq
          CONTRIBUTOR="@${{ github.event.pull_request.user.login }}"
          jq --arg user "$CONTRIBUTOR" '.contributors = (.contributors // []) + [$user] | unique' package.json > temp.json
          mv temp.json package.json

      # Step 4: Commit and push (FIXED - no SSH)
      - name: Commit and push updates
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          git add package.json
          git commit -m "docs: Add @${{ github.event.pull_request.user.login }} as contributor"
          git push

      # Remaining steps unchanged...
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - name: Publish to npm
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          npm version patch -m "Auto-bump: ${{ github.event.head_commit.message || 'Add contributor' }}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.patternidgenerator }}